check for mongodb module existence

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,14 +5,18 @@ before_script:
   - free -m
   - >
       if [ $(phpenv version-name) = "5.6" ]; then
-          echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
+          if ! php -m | grep -q mongo - ; then
+            echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
+          fi
       fi
   - >
       if [ $(phpenv version-name) = "7.1" ] || [ $(phpenv version-name) = "7.2" ]; then
-          pecl channel-update pecl.php.net
-          sleep 5
-          printf "\n" | pecl install -f --ignore-errors mongodb
-          echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
+          if ! php -m | grep -q mongodb - ; then
+            pecl channel-update pecl.php.net
+            sleep 5
+            printf "\n" | pecl install -f --ignore-errors mongodb
+            echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
+          fi
       fi
   - composer install --dev --no-interaction
   - wget https://scrutinizer-ci.com/ocular.phar
